name: "Dev Terraform Workflow"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main  
permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: self-hosted

    # 👇 1️⃣  Job-level environment for Terraform
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: 718e0937-6c20-494e-ac7e-a420f85bb45b
      ARM_TENANT_ID: 9ebcd82b-3a71-49bf-891e-86d819a0911c
      ARM_SUBSCRIPTION_ID: f0641b2c-ae07-4eb4-abb0-7be5a73752cd

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/dev
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev

  terraform-apply:
    runs-on: self-hosted
    needs: terraform-init-plan
    environment: dev      # must match your Azure Federated Credential
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: 718e0937-6c20-494e-ac7e-a420f85bb45b
      ARM_TENANT_ID: 9ebcd82b-3a71-49bf-891e-86d819a0911c
      ARM_SUBSCRIPTION_ID: f0641b2c-ae07-4eb4-abb0-7be5a73752cd

    # Run only on push to main
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: environments/dev
