name: "Dhondhu Maharaj"

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
      - 'hotfix/**'

jobs:
  terraformInit:
    name: Terraform Initwa
    runs-on: dhondhu-maharaj
    steps:
      - name: Dhondhu Maharaj Rocks!
        run: echo "Dhondhu Maharaj"
